from fastapi import APIRouter
from app.models import FeedbackOut

router = APIRouter()

@router.post("/get_feedback")
def get_feedback(user_id: str, problem_id: str):
    # feedback_service + Groq will handle this
    return FeedbackOut(
        user_id=user_id,
        problem_id=problem_id,
        feedback="Feedback will be generated by Groq LLM",
        pattern_detected=None
    )